# Generated by Django 4.2.5 on 2023-09-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_client_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bordereauadministratif",
            name="numero_ordre",
            field=models.CharField(default="", max_length=200, null=True),
        ),
    ]
