# Generated by Django 4.2.5 on 2023-11-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_bordereauadministratif_numero_ordre"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="date_fin",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="num_aggregation",
            field=models.CharField(default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="name",
            field=models.CharField(default="Lingots D'or", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="date_creation",
            field=models.DateTimeField(null=True),
        ),
    ]
