# Generated by Django 4.2.5 on 2023-11-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_invoice_date_fin_invoice_num_aggregation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="date_creation",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="date_fin",
            field=models.DateField(null=True),
        ),
    ]
