# Generated by Django 4.2.5 on 2023-11-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_invoice_date_creation_alter_invoice_date_fin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="num_aggregation",
        ),
        migrations.AddField(
            model_name="client",
            name="num_aggregation",
            field=models.CharField(default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="name",
            field=models.CharField(default="Lingots D'or", max_length=100, null=True),
        ),
    ]
