# Generated by Django 4.2.7 on 2023-12-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_client_date_aggregation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="date_aggregation",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
