# Generated by Django 4.2.7 on 2023-12-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_client_date_aggregation"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="couleur_statut",
            field=models.CharField(
                choices=[("vert", "Vert"), ("rouge", "Rouge"), ("orange", "orange")],
                default="vert",
                max_length=10,
            ),
        ),
    ]
