# Generated by Django 4.0.6 on 2024-01-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_client_date_aggregation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereauadministratif',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
