# Generated by Django 4.2.5 on 2024-01-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_alter_bordereauadministratif_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="date_aggregation_expiree",
            field=models.BooleanField(default=False),
        ),
    ]
